FROM node:alpine
RUN apk update && apk add --no-cache libc6-compat && apk add git
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG PRIVATE_KEY
ARG CLIENT_EMAIL
ARG SPREADSHEET_ID_1
ARG PORT

ENV PRIVATE_KEY=$PRIVATE_KEY
ENV CLIENT_EMAIL=$CLIENT_EMAIL
ENV SPREADSHEET_ID_1=$SPREADSHEET_ID_1
ENV PORT=$PORT

EXPOSE $PORT
CMD ["sh", "-c", "PRIVATE_KEY=${PRIVATE_KEY} CLIENT_EMAIL=${CLIENT_EMAIL} SPREADSHEET_ID_1=${SPREADSHEET_ID_1} PORT=${PORT} node index.js"]